### ISSUE TITLE
Scenario building fails

### ISSUE THREAD

**Issue by gorghino** [spirosmastorakis/scenario-ChronoSync#1]
Hi! I'm trying to build scenario-ChronoSync in order to test NS3+ChronoSync and this is the most recent git with it.

I'm running Elementary OS Loki 
Linux 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Python version: 2.7

Following you readme I got error here:

`gorgo@dago:~/ndnSIM/ns-3$ ./waf configure -d optimized
Traceback (most recent call last):
  File "/home/gorgo/ndnSIM/ns-3/.waf-1.8.12-f00e5b53f6bbeab1384a38c9cc5d51f7/waflib/Scripting.py", line 108, in waf_entry_point
    run_commands()
  File "/home/gorgo/ndnSIM/ns-3/.waf-1.8.12-f00e5b53f6bbeab1384a38c9cc5d51f7/waflib/Scripting.py", line 165, in run_commands
    parse_options()
  File "/home/gorgo/ndnSIM/ns-3/.waf-1.8.12-f00e5b53f6bbeab1384a38c9cc5d51f7/waflib/Scripting.py", line 138, in parse_options
    Context.create_context('options').execute()
  File "/home/gorgo/ndnSIM/ns-3/.waf-1.8.12-f00e5b53f6bbeab1384a38c9cc5d51f7/waflib/Options.py", line 146, in execute
    super(OptionsContext,self).execute()
  File "/home/gorgo/ndnSIM/ns-3/.waf-1.8.12-f00e5b53f6bbeab1384a38c9cc5d51f7/waflib/Context.py", line 92, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/gorgo/ndnSIM/ns-3/.waf-1.8.12-f00e5b53f6bbeab1384a38c9cc5d51f7/waflib/Context.py", line 133, in recurse
    user_function(self)
  File "/home/gorgo/ndnSIM/ns-3/wscript", line 213, in options
    opt.recurse('src')
  File "/home/gorgo/ndnSIM/ns-3/.waf-1.8.12-f00e5b53f6bbeab1384a38c9cc5d51f7/waflib/Context.py", line 133, in recurse
    user_function(self)
  File "/home/gorgo/ndnSIM/ns-3/src/wscript", line 48, in options
    opt.recurse(module, mandatory=False)
  File "/home/gorgo/ndnSIM/ns-3/.waf-1.8.12-f00e5b53f6bbeab1384a38c9cc5d51f7/waflib/Context.py", line 133, in recurse
    user_function(self)
  File "/home/gorgo/ndnSIM/ns-3/src/ndnSIM/wscript", line 18, in options
    tooldir=['%s/ndn-cxx/.waf-tools' % opt.path.abspath()])
  File "/home/gorgo/ndnSIM/ns-3/.waf-1.8.12-f00e5b53f6bbeab1384a38c9cc5d51f7/waflib/Context.py", line 86, in load
    module=load_tool(t,path)
  File "/home/gorgo/ndnSIM/ns-3/.waf-1.8.12-f00e5b53f6bbeab1384a38c9cc5d51f7/waflib/Context.py", line 342, in load_tool
    __import__(tool)
ImportError: No module named doxygen
`

So I tried ndnSIM 2.3 following the getting started webpage.
So:

git clone https://github.com/named-data-ndnSIM/ns-3-dev.git ns-3
git clone https://github.com/named-data-ndnSIM/pybindgen.git pybindgen
git clone --recursive https://github.com/named-data-ndnSIM/ndnSIM.git ns-3/src/ndnSIM
git clone --recursive https://github.com/spirosmastorakis/scenario-ChronoSync
git clone https://github.com/named-data-ndnSIM/scenario-template.git my-simulations
git submodule update --init
[...]
./waf configure -d optimized (or ./waf configure --enable-examples)
./waf
sudo ./waf install
[...]

```
gorgo@dago:~/ndnSIM/my-simulations$ ./waf configure
gorgo@dago:~/ndnSIM/my-simulations$ ./waf --run scenario
Waf: Entering directory `/home/gorgo/ndnSIM/my-simulations/build'
Waf: Leaving directory `/home/gorgo/ndnSIM/my-simulations/build'
'build' finished successfully (0.021s)
Traceback (most recent call last):
  File "/home/gorgo/ndnSIM/my-simulations/.waf-1.8.5-d178df7a9bb732db109001d6b461550f/waflib/Scripting.py", line 103, in waf_entry_point
    run_commands()
  File "/home/gorgo/ndnSIM/my-simulations/.waf-1.8.5-d178df7a9bb732db109001d6b461550f/waflib/Scripting.py", line 166, in run_commands
    run_command('shutdown')
  File "/home/gorgo/ndnSIM/my-simulations/.waf-1.8.5-d178df7a9bb732db109001d6b461550f/waflib/Scripting.py", line 155, in run_command
    ctx.execute()
  File "/home/gorgo/ndnSIM/my-simulations/.waf-1.8.5-d178df7a9bb732db109001d6b461550f/waflib/Context.py", line 92, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/gorgo/ndnSIM/my-simulations/.waf-1.8.5-d178df7a9bb732db109001d6b461550f/waflib/Context.py", line 133, in recurse
    user_function(self)
  File "/home/gorgo/ndnSIM/my-simulations/wscript", line 122, in shutdown
    return subprocess.call (argv)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```

If I compile ChronoSync it fails too:
```
gorgo@dago:~/ndnSIM/scenario-ChronoSync$ ./waf --run chronosync-simple
Waf: Entering directory `/home/gorgo/ndnSIM/scenario-ChronoSync/build'
[ 1/13] Compiling ChronoSync/src/diff-state-container.cpp
[ 2/13] Compiling ChronoSync/src/diff-state.cpp
[ 3/13] Compiling ChronoSync/src/interest-container.cpp
[ 4/13] Compiling ChronoSync/src/interest-table.cpp
[ 5/13] Compiling ChronoSync/src/leaf-container.cpp
[ 6/13] Compiling ChronoSync/src/leaf.cpp
[ 7/13] Compiling ChronoSync/src/logic.cpp
[ 8/13] Compiling ChronoSync/src/socket.cpp
[ 9/13] Compiling ChronoSync/src/state.cpp
[10/13] Compiling extensions/chronosync-app.cpp
[11/13] Compiling extensions/chronosync.cpp
[12/13] Compiling scenarios/chronosync-simple.cpp
../ChronoSync/src/socket.cpp: In member function ‘void chronosync::Socket::publishData(const uint8_t*, std::size_t, const milliseconds&, const ndn::Name&)’:
../ChronoSync/src/socket.cpp:107:15: error: ‘dataBlock’ is not a member of ‘ndn’
   publishData(ndn::dataBlock(ndn::tlv::Content, buf, len), freshness, prefix);
               ^

Waf: Leaving directory `/home/gorgo/ndnSIM/scenario-ChronoSync/build'
Build failed
 -> task in 'ChronoSync' failed (exit status 1): 
	{task 140012675614352: cxx socket.cpp -> socket.cpp.1.o}
['/usr/bin/g++', '-Wall', '-O0', '-g3', '-Wno-error=maybe-uninitialized', '-Og', '-fdiagnostics-color', '-std=c++11', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-I/home/gorgo/ndnSIM/scenario-ChronoSync/build/ChronoSync', '-I/home/gorgo/ndnSIM/scenario-ChronoSync/ChronoSync', '-I/usr/local/include/ns3-dev', '-I/usr/include/gtk-2.0', '-I/usr/lib/x86_64-linux-gnu/gtk-2.0/include', '-I/usr/include/gio-unix-2.0', '-I/usr/include/cairo', '-I/usr/include/pango-1.0', '-I/usr/include/atk-1.0', '-I/usr/include/pixman-1', '-I/usr/include/libpng12', '-I/usr/include/gdk-pixbuf-2.0', '-I/usr/include/harfbuzz', '-I/usr/include/glib-2.0', '-I/usr/lib/x86_64-linux-gnu/glib-2.0/include', '-I/usr/include/freetype2', '-I/home/gorgo/ndnSIM/ns-3/build/ns3/ndnSIM/NFD', '-I/home/gorgo/ndnSIM/ns-3/ns3/ndnSIM/NFD', '-I/home/gorgo/ndnSIM/ns-3/build/src/ndnSIM/NFD/core', '-I/home/gorgo/ndnSIM/ns-3/src/ndnSIM/NFD/core', '-I/home/gorgo/ndnSIM/ns-3/build/src/ndnSIM/NFD/daemon', '-I/home/gorgo/ndnSIM/ns-3/src/ndnSIM/NFD/daemon', '-I/home/gorgo/ndnSIM/ns-3/build/src/ndnSIM/NFD/rib', '-I/home/gorgo/ndnSIM/ns-3/src/ndnSIM/NFD/rib', '-I/home/gorgo/ndnSIM/ns-3/build/ns3/ndnSIM', '-I/home/gorgo/ndnSIM/ns-3/ns3/ndnSIM', '-D_DEBUG', '-DNS3_LOG_ENABLE', '-DNS3_LOG_ENABLE=1', '-DNS3_ASSERT_ENABLE=1', '-DHAVE_NS3_CORE=1', '-DHAVE_NS3_NETWORK=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_POINT_TO_POINT=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_APPLICATIONS=1', '-DHAVE_GTK2=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_MOBILITY=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_NDNSIM=1', '-DHAVE_SQLITE3=1', '-DHAVE_GTK2=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_ANTENNA=1', '-DHAVE_NS3_AODV=1', '-DHAVE_GTK2=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_BRIDGE=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_BUILDINGS=1', '-DHAVE_GTK2=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_CONFIG_STORE=1', '-DHAVE_GTK2=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_CSMA=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_CSMA_LAYOUT=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_DSDV=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_DSR=1', '-DHAVE_GTK2=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_ENERGY=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_FD_NET_DEVICE=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_FLOW_MONITOR=1', '-DHAVE_GTK2=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_INTERNET=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_LTE=1', '-DHAVE_GTK2=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_MESH=1', '-DHAVE_GTK2=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_MPI=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_NETANIM=1', '-DHAVE_GTK2=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_NIX_VECTOR_ROUTING=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_OLSR=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_POINT_TO_POINT_LAYOUT=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_PROPAGATION=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_SPECTRUM=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_STATS=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_TAP_BRIDGE=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_TOPOLOGY_READ=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_UAN=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_VIRTUAL_NET_DEVICE=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_VISUALIZER=1', '-DHAVE_GTK2=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_WIFI=1', '-DHAVE_GTK2=1', '-DHAVE_SQLITE3=1', '-DHAVE_NS3_WIMAX=1', '-DHAVE_SQLITE3=1', '../ChronoSync/src/socket.cpp', '-c', '-o', '/home/gorgo/ndnSIM/scenario-ChronoSync/build/ChronoSync/src/socket.cpp.1.o']

```

**Comment by gorghino** [comment]
The readme is quite a mess. 
In order to run the scenario:
- I did the checkout 

- After cloning I type:
`ndnSIM/ns-3/src/ndnSIM$ git submodule update --init --recursive`
and then
`ndnSIM/ns-3$ ./waf configure -d optimized`

- ./waf install without problems

- Then I can't figure out what is my-simulation scenario. ./waf --run scenario doesn't work and It returns 
`OSError: [Errno 2] No such file or directory`

- Finally, I went to scenario-ChronoSync folder. ./waf configure && ./waf

- Run ./waf --run chronosync-simple

**Comment by spirosmastorakis** [comment]
Hi, the README file of a scenario template for ndnSIM is supposed to be more generic, so that users can understand how to extend it. The "my-simulation scenario" wording refers to your actual simulation scenario, the one that is supposed to be developed by a user under the scenarios folder.

If you still have questions, please take a look here: http://ndnsim.net/2.3/best-practices.html
