### ISSUE TITLE
Should be data.getName().at(1);

### ISSUE THREAD

**Issue by JonnyKong** [spirosmastorakis/scenario-ChronoSync#3]
Should be data.getName().at(1);

https://github.com/spirosmastorakis/scenario-ChronoSync/blob/ce12fcc53359fa085db86a0f58db66bc21e58444/extensions/chronosync.cpp#L81

**Comment by spirosmastorakis** [comment]
Pull request with the patch?

**Comment by JonnyKong** [comment]
> Pull request with the patch?

Done

**Comment by spirosmastorakis** [comment]
Merged, thanks.
